/**
 * Prepare GitHub Pages — builds the landing page index.html with links
 * to all generated artifacts: API docs, coverage reports, and guides.
 *
 * This script runs in the deploy-pages CI job after TypeDoc and coverage
 * artifacts have been collected into docs/.
 */

import { readdirSync, existsSync, writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';

const DOCS_DIR = 'docs';
mkdirSync(DOCS_DIR, { recursive: true });

const pages = {
  'API Reference': { path: 'api/', description: 'TypeDoc-generated API documentation for all packages' },
  'User Guide': { path: 'guide/', description: 'From zero to production — comprehensive user guide' },
  Coverage: { path: 'coverage/', description: 'Per-package coverage reports (Istanbul + v8)' },
};

// Copy user guide into docs/guide/ so Pages can serve it
const guideDir = join(DOCS_DIR, 'guide');
mkdirSync(guideDir, { recursive: true });
if (existsSync('README.md')) {
  writeFileSync(join(guideDir, 'index.html'), wrapMarkdownToHtml('README.md', 'Causality Analyzer — User Guide'));
}

// Generate root index.html
const sections = Object.entries(pages).map(([title, { path, description }]) => {
  const exists = existsSync(join(DOCS_DIR, path));
  const badge = exists ? '✅' : '⏳';
  const link = exists ? `<a href="${path}">${title}</a>` : title;
  return `
    <div class="card">
      <h3>${badge} ${link}</h3>
      <p>${description}</p>
      <p class="path"><code>/${path.replace(/\/$/, '')}</code></p>
    </div>`;
}).join('');

const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Causality Analyzer</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif; max-width: 900px; margin: 40px auto; padding: 0 20px; color: #1e293b; background: #fff; }
    h1 { color: #2563eb; font-size: 2rem; margin-bottom: 8px; }
    h1 span { font-weight: 400; color: #64748b; font-size: 1.2rem; }
    .subtitle { color: #64748b; margin-bottom: 32px; font-size: 1.1rem; }
    .card { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 20px; margin: 16px 0; transition: border-color 0.2s; }
    .card:hover { border-color: #2563eb; }
    .card h3 { color: #1e293b; margin-bottom: 6px; }
    .card h3 a { color: #2563eb; text-decoration: none; }
    .card h3 a:hover { text-decoration: underline; }
    .card p { color: #64748b; font-size: 0.95rem; }
    .card .path { font-size: 0.85rem; margin-top: 6px; }
    .card .path code { background: #e2e8f0; padding: 2px 6px; border-radius: 4px; font-size: 0.85rem; }
    footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e2e8f0; color: #94a3b8; font-size: 0.85rem; }
    footer a { color: #2563eb; }
  </style>
</head>
<body>
  <h1>Causality Analyzer <span>v0.1.0</span></h1>
  <p class="subtitle">Embeddable causal AI library for Node.js — anomaly detection, causal discovery, root cause analysis, effect estimation, and counterfactual reasoning.</p>

  ${sections}

  <footer>
    <p>Generated by CI · <a href="https://github.com/AgentiX-E/causality-analyzer">GitHub</a> ·
    <a href="https://agentix-e.github.io/causality-analyzer/api/">API Docs</a> ·
    <a href="https://agentix-e.github.io/causality-analyzer/coverage/">Coverage</a></p>
  </footer>
</body>
</html>`;

writeFileSync(join(DOCS_DIR, 'index.html'), html);
console.log('[prepare-pages] Root index.html generated');
console.log(`[prepare-pages] Sections: ${Object.keys(pages).length}`);

// ── Helpers ──────────────────────────────────────────────────────────

function wrapMarkdownToHtml(mdPath, title) {
  // Simple: wrap with basic HTML for GitHub Pages serving
  return `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8">
<title>${title}</title>
<meta http-equiv="refresh" content="0;url=https://github.com/AgentiX-E/causality-analyzer">
</head><body><p>See <a href="https://github.com/AgentiX-E/causality-analyzer">GitHub README</a> for documentation.</p></body></html>`;
}
